.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. lovebit_qt test_lovebit_qt
clean: FORCE
	$(MAKE) -C .. lovebit_qt_clean test_lovebit_qt_clean
check: FORCE
	$(MAKE) -C .. test_lovebit_qt_check
lovebit-qt lovebit-qt.exe: FORCE
	 $(MAKE) -C .. lovebit_qt
